inp <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=F)
inp[,1] <- as.Date(inp[,1],format="%d/%m/%Y")
sub <- subset(inp,inp[,1]=="2007-02-01" | inp[,1] == "2007-02-02")
sub[,3] <- as.numeric(sub[,3])
sub[,3] <- as.numeric(sub[,4])
sub[,3] <- as.numeric(sub[,5])
sub[,3] <- as.numeric(sub[,6])
sub[,7] <- as.numeric(sub[,7])
sub[,8] <- as.numeric(sub[,8])
sub[,9] <- as.numeric(sub[,9])
sub$POSIXlt <-  as.POSIXlt(paste(sub[,1],sub[,2],sep=" "))
png(file="plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
##primero
plot(sub$POSIXlt,sub[,3],type="n",xlab = "", ylab="Global Active Power (kilowatts)")
lines(sub$POSIXlt,sub[,3])
##segundo
plot(sub$POSIXlt,sub[,5],type="n",xlab = "datetime", ylab="Voltage")
lines(sub$POSIXlt,sub[,5])
##tercero
plot(sub$POSIXlt,sub[,7],type="n",xlab = "", ylab="Energy sub metering")
lines(sub$POSIXlt,sub[,7])
lines(sub$POSIXlt,sub[,8],col="red")
lines(sub$POSIXlt,sub[,9],col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=2,bty="n")
##cuarto
plot(sub$POSIXlt,sub[,4],type="n",xlab = "datetime", ylab="Global_reactive_power")
lines(sub$POSIXlt,sub[,4])
dev.off()
