inp <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=F)
inp[,1] <- as.Date(inp[,1],format="%d/%m/%Y")
sub <- subset(inp,inp[,1]=="2007-02-01" | inp[,1] == "2007-02-02")
sub[,3] <- as.numeric(sub[,3])
Sys.setenv(TZ="EST")
sub$POSIXlt <-  as.POSIXlt(paste(sub[,1],sub[,2],sep=" "))
png(file="plot2.png",width = 480, height = 480)
plot(sub$POSIXlt,sub[,3],type="n",xlab = "", ylab="Global Active Power (kilowatts)")
lines(sub$POSIXlt,sub[,3])
dev.off()
